= Inteligencia Artificial
:published-at: 2016-07-10
:hp-tags: ia, algoritmos, geneticos

Cuando en los años cuarenta se pusieron a funcionar las primeras computadoras (esos roperos de metal, llenos de bulbos) se les llamó “cerebros electrónicos”, ya que podían hacer sumas. Esto hizo imaginar a muchos: “Mañana las máquinas conversarán con nosotros”. Y entonces el cine, los dibujos animados y la televisión se poblaron de robots “inteligentísimos” —aunque de movimientos algo torpes— que acompañaban a los humanos en toda clase de mundos. Mientras los alumnos de cibernética seguían perforando tarjetas, en el cine la computadora HAL se ponía paranoica y tomaba la decisión de asesinar a los astronautas de la película 2001, Odisea del Espacio. +

La industria de las computadoras no dejó de evolucionar y, de pronto, aquellos enormes aparatos con grandes cintas de carrete se volvieron pequeños y mucho más fáciles de operar. Un día ya tenían un monitor y un teclado para comunicarnos con sus circuitos. Al día siguiente aparecieron en nuestras casas las computadoras personales y hoy están por todos lados, volviéndose indispensables. Los niños de hoy viven en un mundo que, por lo menos en parte, la ciencia ficción imaginó hace 50 años. +

== ¿Puede la inteligencia ser artificial?

La inteligencia artificial (IA) puede definirse como el medio por el cual las computadoras, los robots y otros dispositivos realizan tareas que normalmente requieren de la inteligencia humana. Por ejemplo, la resolución de cierto tipo de problemas, la capacidad de discriminar entre distintos objetos o el responder a órdenes verbales. La IA agrupa un conjunto de técnicas que, mediante circuitos electrónicos y programas avanzados de computadora, busca imitar procedimientos similares a los procesos inductivos y deductivos del cerebro humano. Se basa en la investigación de las redes neuronales humanas y, a partir de ahí, busca copiar electrónicamente el funcionamiento del cerebro. +

El avance en la investigación de las redes neuronales va ganando terreno a una velocidad espectacular. Entre sus aplicaciones destaca la poderosa computadora Deep Blue, que puede vencer a cualquier jugador de ajedrez: no sólo tiene gran cantidad de jugadas programadas, sino que aprende de su adversario, por lo que se va volviendo capaz de adelantarse a las decisiones de su enemigo y hundir sus estrategias antes de que prosperen. +

Esas redes también se han usado en los autos robot, que pueden circular por las autopistas a una velocidad normal con un excelente margen de seguridad, y de hecho han cruzado la Unión Americana de costa a costa sin que el conductor tuviera que tocar el volante o los pedales. Persisten dos problemitas: la cajuela continúa atiborrada de equipo y cuestan un dineral. Pero siguiendo esta línea de avance, es posible que en la próxima década sea común que en la central de autobuses una máquina pregunte al pasajero si desea viajar en un autobús conducido por un humano o guiado por computadora; este último servicio será más seguro y por lo tanto más caro. Se espera que en poco tiempo, imitando el funcionamiento de nuestro cerebro, las computadoras ya no tendrán un gran procesador, sino miles (y más adelante millones) de pequeños procesadores totalmente interconectados entre sí, lo que permitirá la maravillosa capacidad de aprender a través de experiencias recogidas por los “sentidos” de la máquina (cámaras de video, micrófonos, etcétera).